[project]
name = "kkmlmanager"
version = "1.3.0"
requires-python = ">= 3.12.2"
description = "usefule library for ML (mainly for table data)."
dependencies = [
    'kklogger @ git+https://github.com/kazukingh01/kklogger.git@13a5134ec02aa789771bdc082795b22ecdd488a5',
    'pandas==2.2.1',
    'numpy==1.26.4',
    'scikit-learn==1.3.2',
    'matplotlib==3.8.3',
    'joblib==1.4.2',
    'iterative-stratification==0.1.7',
    'optuna==3.6.0',
    'torch==2.5.1+cpu', # pip install --extra-index-url https://download.pytorch.org/whl/cpu -e .
]

[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["kkmlmanager"]
