[project]
name = "kkmlmanager"
version = "1.3.3"
requires-python = ">= 3.12.0"
description = "usefule library for ML (mainly for table data)."
dependencies = [
    'kkgbdt @ git+https://github.com/kazukingh01/kkgbdt.git@acaa3a2715c1a78d6b051cacf805ac6acfe0f41a',
    'matplotlib==3.9.4',
    'polars==1.18.0',
    'pyarrow>=18.1.0',
    'iterative-stratification==0.1.7',
    # 'torch==2.5.1+cpu', # pip install --extra-index-url https://download.pytorch.org/whl/cpu -e .
]

[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["kkmlmanager"]
